# Generated by Django 3.0.6 on 2020-05-17 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('EndDate', models.DateField(help_text='This date must be atleast today')),
                ('Note', models.TextField()),
                ('Adjunto', models.FileField(blank=True, upload_to='')),
                ('X', models.CharField(max_length=25)),
                ('task', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('Type', models.CharField(blank=True, max_length=40, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.User')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
